-- Add new GameType values (existing values untouched, safe additive change)
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'SYNONYM_ANTONYM';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'FILL_GAP_WORD';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'WORD_MEANING_MATCH';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'SITUATION_DIALOGUE_FILL';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'WORD_IN_CONTEXT';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'WORD_SCRAMBLE';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'ODD_ONE_OUT';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'SENTENCE_BUILDER';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'ERROR_SPOTTING';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'FILL_BLANK_GRAMMAR';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'VERB_CONJUGATION';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'MULTIPLE_CHOICE_GRAMMAR';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'LISTEN_FILL_WORD';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'LISTEN_FILL_SENTENCE';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'SPEAK_FILL_WORD';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'SPEAK_FILL_SENTENCE';

-- New enum for the 4 anexes
CREATE TYPE "Anex" AS ENUM ('VOCABULARY', 'GRAMMAR', 'LISTENING_WRITING', 'SPEAKING');

-- New ExerciseSet table, generated from a Lesson's content
CREATE TABLE "ExerciseSet" (
    "id" TEXT NOT NULL,
    "lessonId" TEXT NOT NULL,
    "anex" "Anex" NOT NULL,
    "language" TEXT NOT NULL,
    "level" "CourseLevel" NOT NULL,
    "items" JSONB NOT NULL DEFAULT '[]',
    "generatedBy" TEXT NOT NULL DEFAULT 'gemini',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ExerciseSet_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "ExerciseSet" ADD CONSTRAINT "ExerciseSet_lessonId_fkey"
    FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Game: make legacy vocabularySetId optional, add optional exerciseSetId
ALTER TABLE "Game" ALTER COLUMN "vocabularySetId" DROP NOT NULL;
ALTER TABLE "Game" ADD COLUMN "exerciseSetId" TEXT;

ALTER TABLE "Game" ADD CONSTRAINT "Game_exerciseSetId_fkey"
    FOREIGN KEY ("exerciseSetId") REFERENCES "ExerciseSet"("id") ON DELETE SET NULL ON UPDATE CASCADE;
