// ── Centralized Game Type Metadata ──
// Single source of truth for all game types, categories, and their properties.

export type GameCategory = "vocabulary" | "grammar" | "listening" | "writing";
export type VocabContentType = "words" | "phrases" | "sentences" | "grammar";

export interface GameTypeMeta {
  type: string;
  title: string;
  description: string;
  category: GameCategory;
  emoji: string;
  objectives: string[];
  difficulty: 1 | 2 | 3;
  estimatedTime: string;
  popular?: boolean;
  teacherTip: string;
  example: string;
  vocabContentType: VocabContentType;
  configFields: string[];
}

// ── Category metadata ──
export const CATEGORY_META: Record<
  GameCategory,
  { title: string; subtitle: string; icon: string; color: string; bgColor: string; borderColor: string; gradient: string }
> = {
  vocabulary: {
    title: "Vocabulary",
    subtitle: "Spelling, synonyms, and word meanings",
    icon: "BookOpen",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    gradient: "from-blue-500 to-blue-600",
  },
  grammar: {
    title: "Grammar",
    subtitle: "Tenses, structure, and punctuation",
    icon: "PenTool",
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    gradient: "from-emerald-500 to-emerald-600",
  },
  listening: {
    title: "Listening",
    subtitle: "Phonetics, comprehension, and dictation",
    icon: "Headphones",
    color: "text-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    gradient: "from-purple-500 to-purple-600",
  },
  writing: {
    title: "Writing",
    subtitle: "Creative prompts, essays, and reports",
    icon: "Edit3",
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    gradient: "from-rose-500 to-rose-600",
  },
};

// ── All game types ──
export const GAME_TYPES: GameTypeMeta[] = [
  // ─── VOCABULARY ───
  {
    type: "FLASHCARD",
    title: "Flashcard",
    description: "Flip cards to learn words and translations",
    category: "vocabulary",
    emoji: "🃏",
    objectives: ["Memory Recall", "Word Recognition"],
    difficulty: 1,
    estimatedTime: "8 mins",
    popular: true,
    teacherTip: "Students see the word and try to recall the translation before flipping the card. Great for introducing new vocabulary.",
    example: "Word: 'Apple' → Student guesses 'تفاحة' → flips card to check",
    vocabContentType: "words",
    configFields: [],
  },
  {
    type: "SYNONYM_ANTONYM",
    title: "Synonym & Antonym Match",
    description: "Match words with their synonyms or opposites",
    category: "vocabulary",
    emoji: "🔤",
    objectives: ["Word Relationships", "Vocabulary Depth"],
    difficulty: 2,
    estimatedTime: "10 mins",
    popular: true,
    teacherTip: "Provide a list of words. Students match each word to its synonym or antonym. Excellent for expanding vocabulary networks.",
    example: "Match 'Happy' → 'Joyful' (synonym) or 'Happy' → 'Sad' (antonym)",
    vocabContentType: "words",
    configFields: [],
  },
  {
    type: "FILL_GAP_WORD",
    title: "Fill the Gap",
    description: "Complete sentences by filling missing vocabulary words",
    category: "vocabulary",
    emoji: "📝",
    objectives: ["Context Clues", "Sentence Comprehension"],
    difficulty: 2,
    estimatedTime: "10 mins",
    teacherTip: "Sentences with a blank where a vocabulary word is missing. Students type the correct word. Tests understanding in context.",
    example: "Sentence: 'I eat an ___ every morning.' → Student types 'apple'",
    vocabContentType: "phrases",
    configFields: [],
  },
  {
    type: "WORD_MEANING_MATCH",
    title: "Word & Meaning Match",
    description: "Match words to their definitions",
    category: "vocabulary",
    emoji: "🔍",
    objectives: ["Definition Matching", "Semantic Understanding"],
    difficulty: 1,
    estimatedTime: "10 mins",
    popular: true,
    teacherTip: "Students drag and drop words to connect them with their correct definitions. Great for assessment.",
    example: "Match 'Apple' → 'A red or green fruit' | 'Dog' → 'A pet that barks'",
    vocabContentType: "words",
    configFields: [],
  },
  {
    type: "SITUATION_DIALOGUE_FILL",
    title: "Situational Dialogue",
    description: "Complete real-life conversations by filling in blanks",
    category: "vocabulary",
    emoji: "💬",
    objectives: ["Conversational Fluency", "Practical Usage"],
    difficulty: 2,
    estimatedTime: "12 mins",
    popular: true,
    teacherTip: "A dialogue with missing words. Students fill in the blanks with appropriate vocabulary. Best with phrase-based content.",
    example: "A: 'How ___ are you?' B: 'I'm 12 years old.' → Student fills 'old'",
    vocabContentType: "phrases",
    configFields: [],
  },
  {
    type: "WORD_IN_CONTEXT",
    title: "Word in Context",
    description: "Choose the correct word for each sentence context",
    category: "vocabulary",
    emoji: "📄",
    objectives: ["Contextual Usage", "Word Discrimination"],
    difficulty: 2,
    estimatedTime: "10 mins",
    teacherTip: "Students read a sentence and choose which word fits best from multiple choices. Tests nuanced understanding.",
    example: "Sentence: 'She ___ to school every day.' → Choose: 'go' / 'goes' / 'going'",
    vocabContentType: "phrases",
    configFields: ["optionsCount"],
  },
  {
    type: "WORD_SCRAMBLE",
    title: "Word Scramble",
    description: "Unscramble letters to form vocabulary words",
    category: "vocabulary",
    emoji: "🔀",
    objectives: ["Spelling", "Letter Recognition"],
    difficulty: 1,
    estimatedTime: "8 mins",
    teacherTip: "Letters are jumbled. Students rearrange them to form the correct word. Reinforces spelling.",
    example: "Letters: 'P P L E A' → Student types 'APPLE'",
    vocabContentType: "words",
    configFields: [],
  },
  {
    type: "ODD_ONE_OUT",
    title: "Odd One Out",
    description: "Find which word doesn't belong in the group",
    category: "vocabulary",
    emoji: "🎯",
    objectives: ["Categorization", "Critical Thinking"],
    difficulty: 2,
    estimatedTime: "8 mins",
    popular: true,
    teacherTip: "Show 4-5 words. Students identify the one that doesn't fit the category. Develops analytical skills.",
    example: "Words: 'Apple, Banana, Carrot, Grape' → 'Carrot' is the odd one (vegetable vs fruits)",
    vocabContentType: "words",
    configFields: [],
  },
  {
    type: "FLASHCARD_3D",
    title: "Word Matcher",
    description: "Connect words with their synonyms in a matching game",
    category: "vocabulary",
    emoji: "🃏",
    objectives: ["Synonym Recognition", "Vocabulary Expansion"],
    difficulty: 1,
    estimatedTime: "8 mins",
    teacherTip: "Cards float in space. Students flip and match words to their synonyms. Great for building word relationships.",
    example: "Match 'Happy' → 'Joyful', 'Big' → 'Large'",
    vocabContentType: "words",
    configFields: [],
  },
  {
    type: "COLLOCATION_BUILDER",
    title: "Collocation Builder",
    description: "Build natural word combinations",
    category: "vocabulary",
    emoji: "🧩",
    objectives: ["Natural Phrases", "Word Combinations"],
    difficulty: 3,
    estimatedTime: "12 mins",
    teacherTip: "Students match words that naturally go together (collocations). Builds natural-sounding language skills.",
    example: "Match 'make' → 'a decision' | 'take' → 'a break' | 'do' → 'homework'",
    vocabContentType: "words",
    configFields: [],
  },
  {
    type: "CROSSWORD",
    title: "Vocabulary Crossword",
    description: "Solve a crossword using vocabulary clues",
    category: "vocabulary",
    emoji: "🔄",
    objectives: ["Spelling", "Definition Recall"],
    difficulty: 3,
    estimatedTime: "20 mins",
    teacherTip: "Students fill a crossword grid where clues are definitions or translations of the vocabulary. Challenging and fun.",
    example: "Clue: 'A red fruit (5 letters)' → Answer: 'APPLE'",
    vocabContentType: "words",
    configFields: ["gridSize"],
  },
  {
    type: "PICTURE_TO_WORD",
    title: "Picture to Word Match",
    description: "Match vocabulary words with corresponding images",
    category: "vocabulary",
    emoji: "🖼️",
    objectives: ["Visual Association", "Word Recognition"],
    difficulty: 1,
    estimatedTime: "8 mins",
    teacherTip: "Displays an image (or placeholder), student selects the matching word. Perfect for visual learners.",
    example: "Image of an apple → Student selects 'Apple' from options",
    vocabContentType: "words",
    configFields: [],
  },

  // ─── GRAMMAR ───
  {
    type: "SENTENCE_BUILDER",
    title: "Sentence Builder",
    description: "Arrange scrambled words into correct sentences",
    category: "grammar",
    emoji: "🏗️",
    objectives: ["Sentence Structure", "Word Order"],
    difficulty: 2,
    estimatedTime: "10 mins",
    popular: true,
    teacherTip: "Words are scrambled. Students drag them into the correct grammatical order. Reinforces syntax.",
    example: "Words: 'to / go / school / I / every / day' → 'I go to school every day.'",
    vocabContentType: "sentences",
    configFields: [],
  },
  {
    type: "ERROR_SPOTTING",
    title: "Error Spotting",
    description: "Find and correct grammar mistakes in sentences",
    category: "grammar",
    emoji: "🔎",
    objectives: ["Error Identification", "Grammar Rules"],
    difficulty: 2,
    estimatedTime: "10 mins",
    popular: true,
    teacherTip: "Show a sentence with an error. Students identify and fix the mistake. Tests active grammar knowledge.",
    example: "Sentence: 'He go to school yesterday.' → Error: 'go' should be 'went'",
    vocabContentType: "sentences",
    configFields: [],
  },
  {
    type: "FILL_BLANK_GRAMMAR",
    title: "Fill the Blank (Grammar)",
    description: "Complete with the correct grammatical form",
    category: "grammar",
    emoji: "✍️",
    objectives: ["Verb Forms", "Tense Usage"],
    difficulty: 2,
    estimatedTime: "10 mins",
    teacherTip: "Sentences with a blank. Students type the word in the correct grammatical form.",
    example: "Sentence: 'She ___ (play) tennis every Sunday.' → Student types 'plays'",
    vocabContentType: "sentences",
    configFields: [],
  },
  {
    type: "VERB_CONJUGATION",
    title: "Verb Conjugation",
    description: "Practice verb conjugations across tenses",
    category: "grammar",
    emoji: "🔄",
    objectives: ["Tense Mastery", "Verb Forms"],
    difficulty: 3,
    estimatedTime: "12 mins",
    popular: true,
    teacherTip: "Given a verb and tense, students fill in the conjugated forms for each pronoun. Essential for fluency.",
    example: "Verb: 'to be' (Past) → I ___ / You ___ / He ___ / We ___",
    vocabContentType: "grammar",
    configFields: [],
  },
  {
    type: "MULTIPLE_CHOICE_GRAMMAR",
    title: "Multiple Choice Grammar",
    description: "Choose the grammatically correct option",
    category: "grammar",
    emoji: "☑️",
    objectives: ["Grammar Rules", "Sentence Correction"],
    difficulty: 1,
    estimatedTime: "8 mins",
    teacherTip: "A sentence with a grammar choice. Students pick the correct option. Quick assessment tool.",
    example: "Sentence: 'She ___ to school yesterday.' → Options: 'go' / 'goes' / 'went' / 'going'",
    vocabContentType: "sentences",
    configFields: ["optionsCount"],
  },
  {
    type: "DRAG_DROP",
    title: "Drag & Drop Grammar",
    description: "Match sentence parts together",
    category: "grammar",
    emoji: "🧩",
    objectives: ["Sentence Structure", "Part of Speech"],
    difficulty: 2,
    estimatedTime: "10 mins",
    teacherTip: "Students drag sentence fragments into the correct positions to form proper sentences.",
    example: "Fragment 'The cat' → 'is sleeping' → 'on the sofa'",
    vocabContentType: "sentences",
    configFields: [],
  },
  {
    type: "QUIZ",
    title: "Grammar Quiz",
    description: "Test grammar knowledge with mixed questions",
    category: "grammar",
    emoji: "❓",
    objectives: ["Comprehensive Review", "Grammar Application"],
    difficulty: 2,
    estimatedTime: "10 mins",
    teacherTip: "Mixed grammar questions covering various topics. Great for review sessions and assessment.",
    example: "Q: 'Which is correct? A) He don't like B) He doesn't like C) He not like'",
    vocabContentType: "sentences",
    configFields: ["optionsCount"],
  },

  // ─── LISTENING ───
  {
    type: "DICTATION",
    title: "Dictation Challenge",
    description: "Listen and type exactly what you hear",
    category: "listening",
    emoji: "🎧",
    objectives: ["Listening Accuracy", "Spelling"],
    difficulty: 3,
    estimatedTime: "15 mins",
    popular: true,
    teacherTip: "Play an audio clip. Students listen and type the exact words they hear. Excellent for ear training.",
    example: "Audio says: 'The weather is beautiful today.' → Student types that sentence",
    vocabContentType: "sentences",
    configFields: ["audioSource"],
  },
  {
    type: "LISTEN_FILL_WORD",
    title: "Listen & Fill",
    description: "Listen and fill in missing words from audio",
    category: "listening",
    emoji: "🎧",
    objectives: ["Word Recognition", "Listening Comprehension"],
    difficulty: 2,
    estimatedTime: "10 mins",
    teacherTip: "Play audio with a transcript that has gaps. Students fill the missing words.",
    example: "Audio: 'I ___ to school.' + Transcript with gap → Student types 'walk'",
    vocabContentType: "sentences",
    configFields: ["audioSource"],
  },
  {
    type: "LISTEN_FILL_SENTENCE",
    title: "Listen & Order",
    description: "Listen and arrange words in correct order",
    category: "listening",
    emoji: "🔊",
    objectives: ["Sentence Processing", "Audio Comprehension"],
    difficulty: 2,
    estimatedTime: "10 mins",
    teacherTip: "Play a sentence audio. Students arrange scrambled words into the correct order.",
    example: "Audio: 'I like apples.' → Words: 'apples / like / I' → Order: 'I like apples'",
    vocabContentType: "sentences",
    configFields: ["audioSource"],
  },
  {
    type: "SPEED_ROUND",
    title: "Listen & Select",
    description: "Listen and pick the right answer quickly",
    category: "listening",
    emoji: "⚡",
    objectives: ["Quick Recognition", "Audio-Visual Matching"],
    difficulty: 1,
    estimatedTime: "8 mins",
    teacherTip: "Fast-paced: play audio, show options, students select the correct one before time runs out.",
    example: "Audio: 'Apple' → Images: 🍎 🚗 📚 → Student taps 🍎 quickly",
    vocabContentType: "words",
    configFields: ["audioSource"],
  },
  {
    type: "MINIMAL_PAIR",
    title: "Minimal Pair Match",
    description: "Distinguish between similar sounds",
    category: "listening",
    emoji: "🔊",
    objectives: ["Sound Discrimination", "Pronunciation"],
    difficulty: 3,
    estimatedTime: "12 mins",
    teacherTip: "Perfect for pronunciation! Students hear similar word pairs and identify which is which.",
    example: "Audio: 'ship' vs 'sheep' → Student selects the correct word they heard",
    vocabContentType: "words",
    configFields: [],
  },

  // ─── WRITING ───
  {
    type: "STORY",
    title: "Story Builder",
    description: "Build stories from guided writing prompts",
    category: "writing",
    emoji: "📖",
    objectives: ["Creative Writing", "Narrative Structure"],
    difficulty: 2,
    estimatedTime: "25 mins",
    popular: true,
    teacherTip: "Provide a story starter or outline. Students write paragraphs following the structure.",
    example: "Prompt: 'Write about your last vacation. Include where you went, who with, and what you did.'",
    vocabContentType: "sentences",
    configFields: ["storyPrompt"],
  },
  {
    type: "FILL_BLANK",
    title: "Fill & Rewrite",
    description: "Rewrite sentences to improve them",
    category: "writing",
    emoji: "✏️",
    objectives: ["Sentence Improvement", "Writing Style"],
    difficulty: 2,
    estimatedTime: "12 mins",
    teacherTip: "Show a sentence with room for improvement. Students rewrite it more clearly or correctly.",
    example: "Before: 'The cat is big.' → Students rewrite: 'The large gray cat is sleeping peacefully.'",
    vocabContentType: "sentences",
    configFields: [],
  },
  {
    type: "SPEAK_FILL_WORD",
    title: "Speak & Fill Word",
    description: "Listen to audio and speak the missing word",
    category: "listening",
    emoji: "🎙️",
    objectives: ["Pronunciation", "Oral Fluency"],
    difficulty: 2,
    estimatedTime: "10 mins",
    teacherTip: "Students listen to a sentence with a missing word and speak the correct word. Combines listening and speaking.",
    example: "Audio: 'I ___ to school every day.' → Student speaks 'go'",
    vocabContentType: "sentences",
    configFields: ["audioSource"],
  },
  {
    type: "SPEAK_FILL_SENTENCE",
    title: "Speak & Complete",
    description: "Listen and speak the complete sentence",
    category: "listening",
    emoji: "🗣️",
    objectives: ["Oral Fluency", "Sentence Memory"],
    difficulty: 3,
    estimatedTime: "12 mins",
    teacherTip: "Students listen to a sentence and repeat it aloud. Tests pronunciation and sentence-level fluency.",
    example: "Audio: 'The weather is beautiful today.' → Student speaks the full sentence",
    vocabContentType: "sentences",
    configFields: ["audioSource"],
  },
];

// ── Lookup helpers ──

export function getGameTypeMeta(type: string): GameTypeMeta | undefined {
  return GAME_TYPES.find((g) => g.type === type);
}

export function getGameTypesByCategory(category: GameCategory): GameTypeMeta[] {
  return GAME_TYPES.filter((g) => g.category === category);
}

export function getPopularGameTypes(): GameTypeMeta[] {
  return GAME_TYPES.filter((g) => g.popular);
}

export const TYPE_EMOJI: Record<string, string> = Object.fromEntries(
  GAME_TYPES.map((g) => [g.type, g.emoji])
);

export const TYPE_LABELS: Record<string, string> = Object.fromEntries(
  GAME_TYPES.map((g) => [g.type, g.title])
);

// ── Poster card visual themes ──
export const POSTER_THEMES: Record<string, { bg: string; overlay: string; iconColor: string }> = {
  vocabulary: { bg: "bg-blue-100", overlay: "from-blue-600/80 to-blue-400/0", iconColor: "text-blue-600" },
  grammar: { bg: "bg-emerald-100", overlay: "from-emerald-600/80 to-emerald-400/0", iconColor: "text-emerald-600" },
  listening: { bg: "bg-purple-100", overlay: "from-purple-600/80 to-purple-400/0", iconColor: "text-purple-600" },
  writing: { bg: "bg-rose-100", overlay: "from-rose-600/80 to-rose-400/0", iconColor: "text-rose-600" },
};

// ── Vocab content type labels (shown in the UI) ──
export const VOCAB_CONTENT_LABELS: Record<VocabContentType, { label: string; hint: string }> = {
  words: { label: "Words", hint: "This game works best with individual vocabulary words and their translations." },
  phrases: { label: "Phrases", hint: "This game works best with phrases and short expressions, not just single words." },
  sentences: { label: "Sentences", hint: "This game works best with complete example sentences." },
  grammar: { label: "Grammar Items", hint: "This game needs grammar-focused content like verb forms and rules." },
};
