-- Ported Language-Games engine types
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'CATEGORY_SORT';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'TRANSFORMATION';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'WRITING_RUBRIC';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'SPEAKING';
